CC = clang -Wall

EX1 = 

EX2a = 

EX2b = 

PROGS=$(EX1) $(EX2a) $(EX2b)

all: $(PROGS)

$(EX1):
	$(CC) $(EX1).c -o $(EX1)

$(EX2a):
	$(CC) $(EX2a).c -o $(EX2a)

$(EX2b):
	$(CC) $(EX2b).c -o $(EX2b)

clean:
	rm $(PROGS)